Add events and statistics to HTTP API request processing
mozilla-services/reaper pull request #82
Opened 2016-08-31 20:18 UTC by milescrabill

@oremj  r+?

2016-09-14 21:13 UTC, oremj commented on reaper/http.go
> +			reaperevents.NewEvent("Reaper: Delay Request Received", fmt.Sprintf("Delay for %s in region %s until %s", job.ID, job.Region, job.IgnoreUntil.String()), nil, []string{})
Nitpick, would be nice to break this up in to a few lines to make it shorter.

2016-09-14 21:14 UTC, oremj requested changes

2016-09-19 21:04 UTC, milescrabill commented on reaper/http.go
> +			reaperevents.NewEvent("Reaper: Delay Request Received", fmt.Sprintf("Delay for %s in region %s until %s", job.ID, job.Region, job.IgnoreUntil.String()), nil, []string{})
Fixed, also broke up a few others.

2016-09-20 21:42 UTC, oremj approved these changes

2016-09-20 21:42 UTC, oremj commented
LGTM

2016-09-20 21:43 UTC, merged