Improve DryRun behavior
mozilla-services/reaper pull request #98
Opened 2016-10-27 22:49 UTC by milescrabill

Simplify DefaultOwner - now just an email address

add lots of logging for EventReporters when they trigger (with logging extras enabled), make them more sensitive to DryRuns, and generally improve DryRun logging

@oremj r?

2016-10-27 22:51 UTC, milescrabill commented on events/mailer.go
> +	NewCountStatistic("reaper.emails.sent", []string{to.Address})
I threw this in... good thing to track. Doesn't necessarily belong in this PR, whoops.

2016-10-28 00:43 UTC, oremj requested changes

2016-10-28 00:43 UTC, oremj commented on aws/resource.go
> +		log.Error("Resource Owner() failed: ", err.Error())
err could be nil here, so err.Error() could cause a panic.

2016-10-28 00:43 UTC, oremj commented on events/datadog.go
> +		port, err = strconv.Atoi(e.Config.Port)
I looks like this error will be logged twice. This function should probably just be refactored to handle the errors when they happen.

2020-08-10 18:33 UTC, closed without merging